version: "3.8"
services:
  rmv:
    image: rmv_chore:latest
    container_name: rmv_chore_compose_dev_container
    volumes:
      - ./src:/home/devuser/src
      - ./tests:/home/devuser/tests
    working_dir: /home/devuser/src
    command: bash
    tty: true
