@startuml classes
set namespaceSeparator none
class "BaseGraph" as library.tf_management.graph.BaseGraph #99DDFF {
  _graph : DiGraph
  _graph_lock : _RLock
  _lock_main_frame : _RLock
  _main_frame : str
  _running : bool
  _worker_thread : Thread
  begin
  count : int
  rmv_params
  __del__()
  __init__(rmv_params: RmvParameters)
  _removeExpiredEdges()
  {abstract}_update()
  _workerLoop()
}
class "BaseMessage" as library.markers_management.markers.BaseMessage #EE8866 {
  message_type : Type[Marker | MarkerArray]
  __init__(message_type: Type[Marker | MarkerArray])
  {abstract}process(message, time: Time)
}
class "CameraExtrinsics" as library.utils.camera.CameraExtrinsics #BBCC33 {
  extrinsic_matrix
  params
  __init__(params: VisualizationParameters)
}
class "CameraIntrinsics" as library.utils.camera.CameraIntrinsics #BBCC33 {
  intrinsic_matrix
  params
  __init__(params: VisualizationParameters)
}
class "CameraManager" as library.utils.camera.CameraManager #BBCC33 {
  __extrinsics
  __intrinsics
  __params
  camera_distance
  fov
  fx
  __init__(params: VisualizationParameters)
  projectToImage(point_camera: np.ndarray) -> Tuple[int, int] | None
  worldToCamera(point: np.ndarray) -> np.ndarray
}
class "FramesParameters" as library.parameters.frame_parameter.FramesParameters #77AADD {
  _axes_length : float
  _locks : dict
  _main_frame : str
  _show_axes : bool
  _show_connections : bool
  _show_frame_names : bool
  _sub_frames : List[str]
  axes_length
  main_frame
  show_axes
  show_connections
  show_frame_names
  sub_frames
  {abstract}__init__() -> None
  __post_init__()
  toggleAxes() -> None
  toggleConnections() -> None
  toggleFrameNames() -> None
  updateSubFrame(frame_list: List) -> None
}
class "MarkerArrayMessage" as library.markers_management.markers.MarkerArrayMessage #EE8866 {
  __init__()
  process(message: MarkerArray, time: Time) -> List[MarkerRmv]
}
class "MarkerMessage" as library.markers_management.markers.MarkerMessage #EE8866 {
  __init__()
  process(message: Marker, time: Time) -> MarkerRmv
}
class "MarkerRmv" as library.markers_management.markers.MarkerRmv #EE8866 {
  __eq__(value)
  __init__(marker: Marker, current_time: Time)
}
class "MarkerRmvBase" as library.markers_management.markers.MarkerRmvBase #EE8866 {
  _marker : Marker
  _modified_pose : NoneType, Pose
  _pub_time
  color
  frame_id
  identifier
  lifetime
  modified_pose
  points
  pose
  scale
  type
  __init__(marker: Marker, reception_time: Time)
  getTransform()
  isExpired(current_time: Time) -> bool
}
class "MarkersHandler" as library.markers_management.markers.MarkersHandler #EE8866 {
  __delete_markers_thread : Optional[Thread]
  __lock_markers_list : _RLock
  __lock_new_msgs : _RLock
  __markers : dict[tuple[str, int], MarkerRmv]
  __merge_markers_thread : Optional[Thread]
  __new_markers : dict[tuple[str, int], MarkerRmv]
  __new_msgs : List[MarkerArray | Marker]
  __node : Node
  __running : bool
  markers
  __del__()
  __init__(node: Node)
  __mergeNewMarkers()
  __processMessage()
  _deleteExpiredMarkers()
  addMarker(marker: Marker | MarkerArray)
  clearMarkersList()
}
class "RMVChoreNode" as rmv_chore.main.RMVChoreNode #AAAA00 {
  markers_handler
  parameters
  tf_manager
  topic_manager
  transform_graph
  visualization
  __init__()
  projectToMainFrame(markers: List[MarkerRmv], transforms: List[TransformDrawerInfo]) -> List[MarkerRmv]
  visualize()
}
class "RmvParameters" as library.parameters.params.RmvParameters #77AADD {
  __path : str
  frames
  visualization
  __init__(path: str)
  _applyDefaults(data: Dict) -> Dict
  _loadYaml() -> Dict
  _mergeDefaults(defaults: Dict, data: Dict) -> Dict
  _saveYaml()
  _update_frames(data: Dict[str, Any]) -> None
  _update_visualization(data: Dict[str, Any]) -> None
  convertData(data: Any) -> Any
  get()
  set(value)
}
class "RmvTransform" as library.tf_management.transform_rmv.RmvTransform #99DDFF {
  _drawer_info
  _initial_direction : bool
  drawer_info
  __eq__(value) -> bool
  __hash__() -> int
  __init__(transform_stamped: TransformStamped, static: bool)
  updateTransformDrawerInfo(main_frame: str, pose_in_main_frame: Transform, start_connection: Transform, end_connection: Transform) -> None
}
class "SubscriptionManager" as library.topic_management.subscription_manager.SubscriptionManager #44BB99 {
  __subscriptions : Dict[str, Subscription]
  _node : Node
  active_topics
  marker_handler
  __init__(node: Node, markers_handler: MarkersHandler)
  _getMessageType(type_string: str) -> Type[Marker | MarkerArray]
  callback(message: Marker | MarkerArray)
  subscribe(topic: str, topic_type: str)
  unsubscribe(topic: str)
}
class "TFManager" as library.tf_management.tf.TFManager #99DDFF {
  node : Node
  transform_graph
  __init__(node: Node, transform_graph: TransformGraph) -> None
  tfCallback(msg: TFMessage) -> None
  tfStaticCallback(msg: TFMessage) -> None
}
class "TopicManager" as library.topic_management.topic_manager.TopicManager #44BB99 {
  __findMarkersTopics()
  __findMarkersTopicsCallBack() -> None
  __init__(node: Node, markers_handler: MarkersHandler) -> None
  _filter(topics: List[Tuple[str, List[str]]], expected_types: List[str]) -> List[Tuple[str, str]]
  _hasMatchingType(received_types: List[str], expected_types: List[str]) -> str | None
  _hasPublisher(topic: str) -> bool
  _removeUnpublishedTopics(filtered_topics: List[Tuple[str, str]]) -> None
  _subscribeToTopics(filtered_topics: List[Tuple[str, str]]) -> None
}
class "TransformBase" as library.tf_management.transform_rmv.TransformBase #99DDFF {
  __expiration_duration : float
  _name : str
  _parent : str
  _static : bool
  _timestamp : float
  _transform : Transform
  isExpired
  name
  opacity
  parent
  transform
  __eq__(value) -> bool
  __init__(transform_stamped: TransformStamped, static: bool)
  update(transform_stamped: TransformStamped) -> None
}
class "TransformDrawerInfo" as library.tf_management.transform_rmv.TransformDrawerInfo #99DDFF {
  __associated_transform
  _end_connection : Transform
  _main_frame : str
  _pose_in_main_frame : Transform
  _start_connection : Transform
  end_connection
  main_frame
  opacity
  parent
  pose_in_main_frame
  start_connection
  transform_name
  __init__(Transform_base: TransformBase)
  __repr__()
  __str__() -> str
  toDraw(main_frame) -> bool
  update(main_frame: str, pose_in_main_frame: Transform, start_connection: Transform, end_connection: Transform) -> None
}
class "TransformGraph" as library.tf_management.graph.TransformGraph #99DDFF {
  _main_frame
  frames
  main_frame
  __init__(rmv_params: RmvParameters)
  _computeTransformInfo(path: List[str])
  _update()
  addTransform(transform_stamped: TransformStamped, static: bool)
  getTransform(parent: str, child: str) -> Optional[Transform]
  getTransformsFromMainFrame() -> List[TransformDrawerInfo]
  inverseTransformMsg(transform_stamped: TransformStamped) -> TransformStamped
}
class "Visualization" as visualization.visualization.Visualization #EEDD88 {
  bridge : CvBridge
  image : NoneType, ndarray
  node : Node
  publisher_raw
  rmv_params
  transform_graph
  web_server
  __init__(node: Node, params: RmvParameters, transform_graph: TransformGraph)
  resetImage()
  updateImage(markers: List[MarkerRmv])
  visualize(markers: List[MarkerRmv])
}
class "VisualizationParameters" as library.parameters.visualization_parameter.VisualizationParameters #77AADD {
  _background_color : Dict[str, int]
  _camera : Dict[str, Dict[str, Any]]
  _draw_grid : bool
  _fov_deg : int
  _fps : int
  _grid_color : Dict[str, int]
  _grid_spacing : float
  _height : int
  _locks : dict
  _width : int
  background_color
  camera_position
  draw_grid
  fov
  fps
  grid_color
  grid_spacing
  height
  resolution
  width
  {abstract}__init__() -> None
  __post_init__()
  updateBackgroundColor(r: int, g: int, b: int) -> None
  updateCameraPosition(x: Optional[float], y: Optional[float], z: Optional[float], theta: Optional[float]) -> None
  updateGridColor(r: Optional[int], g: Optional[int], b: Optional[int]) -> None
}
class "WebServer" as visualization.visualization.WebServer #EEDD88 {
  app : Flask
  image : ndarray
  server_thread : Thread
  __init__()
  generateFrames()
  runServer()
  updateImage(image: np.ndarray)
  videoFeed()
}
library.markers_management.markers.MarkerArrayMessage --|> library.markers_management.markers.BaseMessage
library.markers_management.markers.MarkerMessage --|> library.markers_management.markers.BaseMessage
library.markers_management.markers.MarkerRmv --|> library.markers_management.markers.MarkerRmvBase
library.tf_management.graph.TransformGraph --|> library.tf_management.graph.BaseGraph
library.tf_management.transform_rmv.RmvTransform --|> library.tf_management.transform_rmv.TransformBase
library.topic_management.topic_manager.TopicManager --|> library.topic_management.subscription_manager.SubscriptionManager
visualization.visualization.Visualization --|> library.utils.camera.CameraManager
library.markers_management.markers.MarkersHandler -u-* rmv_chore.main.RMVChoreNode : markers_handler
library.parameters.frame_parameter.FramesParameters -u-* library.parameters.params.RmvParameters : frames
library.parameters.params.RmvParameters -u-* rmv_chore.main.RMVChoreNode : parameters
library.parameters.visualization_parameter.VisualizationParameters -u-* library.parameters.params.RmvParameters : visualization
library.tf_management.graph.TransformGraph -u-* rmv_chore.main.RMVChoreNode : transform_graph
library.tf_management.tf.TFManager -u-* rmv_chore.main.RMVChoreNode : tf_manager
library.tf_management.transform_rmv.TransformDrawerInfo --* library.tf_management.transform_rmv.RmvTransform : _drawer_info
library.topic_management.topic_manager.TopicManager -u-* rmv_chore.main.RMVChoreNode : topic_manager
library.utils.camera.CameraExtrinsics -u-* library.utils.camera.CameraManager : __extrinsics
library.utils.camera.CameraIntrinsics -u-* library.utils.camera.CameraManager : __intrinsics
visualization.visualization.Visualization -u-* rmv_chore.main.RMVChoreNode : visualization
visualization.visualization.WebServer -u-* visualization.visualization.Visualization : web_server
library.markers_management.markers.MarkersHandler -u-o library.topic_management.subscription_manager.SubscriptionManager : marker_handler
library.parameters.params.RmvParameters --o library.tf_management.graph.BaseGraph : rmv_params
library.parameters.params.RmvParameters -u-o visualization.visualization.Visualization : rmv_params
library.parameters.visualization_parameter.VisualizationParameters --o library.utils.camera.CameraExtrinsics : params
library.parameters.visualization_parameter.VisualizationParameters --o library.utils.camera.CameraIntrinsics : params
library.parameters.visualization_parameter.VisualizationParameters -u-o library.utils.camera.CameraManager : __params
library.tf_management.graph.TransformGraph --o library.tf_management.tf.TFManager : transform_graph
library.tf_management.graph.TransformGraph --o visualization.visualization.Visualization : transform_graph
library.tf_management.transform_rmv.TransformBase --o library.tf_management.transform_rmv.TransformDrawerInfo : __associated_transform
@enduml
