RMV:
  frames:
    axes_length: 0.1
    main_frame: ""
    show_axes: false
    show_connections: true
    show_frame_names: true
    show_sub_frames: false
    sub_frames:
    - ""
  visualizations:
    background_color:
      b: 25
      g: 25
      r: 25
    camera:
      fov_deg: 60
      position:
        theta: 0
        x: 0
        y: 0
        z: 5.0
    draw_grid: true
    fps: 10
    grid_color:
      b: 255
      g: 255
      r: 255
    grid_spacing: 1.0
    height: 500
    width: 800
