RMV:
  # Parameters related to visualization
  visualizations:
    # Parameters related to the image
    width: 800
    height: 500
    fps: 30
    draw_grid: true
    background_color:
      r: 0
      g: 0
      b: 0
    grid_color:
      b: 0.5
      g: 0.5
      r: 0.5
    # Parameters related to the camera
    camera:
      position:
        x: 0
        y: 0
        z: 5
        theta: 0 #degrees
      fov_deg: 60