RMV:
  visualizations:
    background_color:
      b: 25
      g: 25
      r: 25
    camera:
      fov_deg: 60
      position:
        theta: 0
        x: 0
        y: 0
        z: 3
    draw_grid: true
    fps: 30
    grid_color:
      b: 125
      g: 125
      r: 125
    height: 500
    width: 800
    grid_spacing: 0.1 # m
  
  frames:
    main_frame: "frame_1"
    sub_frames: []
    show_axes: true
    show_frame_names: true
    show_connections: true
    axes_length: 0.1 # m
